
subjects = ["c","c++","java","python","andorid","os","toc"]
'''print(subjects)
print(subjects[0])
print(subjects[3:])
print(subjects[-1])'''
print("python" in subjects)
print(subjects + ["swift",27])
# print(subjects*3)
print("Length of the list is :",len(subjects))
subjects.append("basic")
print(subjects)
subjects.insert(5,"rube")
print(subjects)
subjects.sort()
print("After sorting\n ",subjects)
subjects.reverse()
print("After reversing\n",subjects)
subjects2 = subjects.copy()
subjects.pop()
print("After poping :\n",subjects)
# subjects.clear()
# print("The list is clear :\n",subjects)
print("Printing subjects2 :\n",subjects2)
pos = subjects.index("python")
print("positoin of python on list is :",pos)
lists = [1,2,2,3,2,4,5]
pos = lists.count(2)
print(pos)